export const ERROR_RESPONSES = {
    AUTH: {
        EMAIL_EXISTS: 'EMAIL_EXISTS',
        WRONG_PASSWORD_OR_USERNAME: 'WRONG_PASSWORD_OR_USERNAME',
        UNAUTHORIZED: {
            INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
            INVALID_SESSION: 'INVALID_SESSION',
            NO_AUTH_USER: 'NO_AUTH_USER',
            NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
        },
    },
    FILE: {
        UPLOAD_ERROR: 'UPLOAD_ERROR',
        DELETE_ERROR: 'DELETE_ERROR',
        NO_USER_FILE_EXISTS: 'NO_USER_FILE_EXISTS',
    },
    USER: {
        NO_USER_FOUND: 'NO_USER_FOUND',
    },
    GLOBAL: {
        NOT_FOUND: 'NOT_FOUND',
        VALIDATION_ERROR: 'VALIDATION_ERROR',
    },
    COMMENT: {
        NO_COMMENT_FOUND: 'NO_COMMENT_FOUND',
        FORBIDDEN: 'FORBIDDEN',
    },
};
